### ISSUE TITLE
Redirecting the `task` command output also lists the CWD contents

### ISSUE THREAD

**Issue by bergercookie** [go-task/task#1012]
Hi  there,

I'm running `task --list` to list all the available tasks and this runs fine:

```
~/a$ go-task --list
task: Available tasks for this project:
* hello:       Some description
```

I then try to redirect this output to a variable to then do some basic checks on it - I'm using `$(...)` to do this.

```
~/a$ a=$(go-task --list-all); echo $a
task: Available tasks for this project: taskfile_config.env Taskfile.yaml hello: Some description
berger@spitfire ~/a$
```

In this case alongside the command `hello` it also lists the contents of the current working directory.

I'm reproducing this on `bash` as well as `fish` shell, so neither the shell nor my local configuration should have anything to do with it.

I cannot reproduce this when also issuing the `--json` flag

```
$ a=$(go-task --list --json); echo $a
{ "tasks": [ { "name": "hello", "desc": "Some description", "summary": "", "up_to_date": false } ] }
```
 
- Task version: 3.20
- Operating System: Ubuntu 20.04

**Comment by pd93** [comment]
@bergercookie I'm not able to reproduce this. Are you able to provide a sample Taskfile?

**Comment by bergercookie** [comment]
Oops, I thought I already had.
Here you go.

```
version: "3"

tasks:
  hello:
    desc: "Some description"
    cmds:
      - echo "Kalimera {{.ROOT_DIR}}"
```

**Comment by mrhillsman** [comment]
I was able to replicate the error

```shell
[mrhillsman@mhillsma task-help]$ cat Taskfile.yaml 
version: "3"

tasks:
  hello:
    desc: "Some description"
    cmds:
      - echo "Kalimera {{.ROOT_DIR}}"
[mrhillsman@mhillsma task-help]$ ls -lha
total 4.0K
drwxr-xr-x. 1 mrhillsman mrhillsman   34 Feb 19 21:58 .
drwxr-xr-x. 1 mrhillsman mrhillsman 3.7K Feb 19 21:57 ..
-rw-r--r--. 1 mrhillsman mrhillsman    0 Feb 19 21:58 file
-rw-r--r--. 1 mrhillsman mrhillsman  107 Feb 19 21:57 Taskfile.yaml
[mrhillsman@mhillsma task-help]$ echo $(task --list)
task: Available tasks for this project: file Taskfile.yaml hello: Some description
[mrhillsman@mhillsma task-help]$ echo $(task --list-all)
task: Available tasks for this project: file Taskfile.yaml hello: Some description
[mrhillsman@mhillsma task-help]$
```

**Comment by mrhillsman** [comment]
The reason for this is the echo command is interpreting the asterisk (*) that is output before the task name.

```sh
[mrhillsman@mhillsma task-help]$ echo *
file Taskfile.yaml
```

**Comment by pd93** [comment]
@mrhillsman Thanks for helping to reproduce. I wasn't able to reproduce because I'm using ZSH. This only appears to happen with Bash.

Regardless, if you're trying to get a list of tasks, I do not recommend using the output of `task --list` or `task --list-all`. It is formatted for human readability, not scripts. Instead, you should use the `--silent` flag alongside the `--list` and `--list-all` flags.

If you really want the full human-readable output then you need to quote the output of your subshell! e.g.
```
echo "$(task --list)"
```
Note the double quotes (`"`) around the subshell. I recommend giving [this Shellcheck wiki article](https://www.shellcheck.net/wiki/SC2086) a read and also installing Shellcheck into your editor/IDE as it will highlight issues like this for you.

**Comment by mrhillsman** [comment]
@pd93 nice.

@bergercookie, you should also note it is possible it is not bash specific, but echo does say in its man page that its behavior is shell specific.

@pd93 Double quotes make sense. Would single quotes ensure no additional interpolation?

**Comment by pd93** [comment]
> it is possible it is not bash specific, but echo does say in its man page that its behavior is shell specific.

Apologies, I worded my reply badly. It is not necessarily Bash specific, it's just that it does not occur when using ZSH. As you said, `echo` is a shell builtin so its behaviour will change depending on the shell. Having said that, quoting strings generated from subshell commands is a good habit to have no matter what shell you are using.

> Would single quotes ensure no additional interpolation?

Using single quotes will always print the raw string between the quotes with no interpolation. So in fact, the subshell command will not run at all. e.g.
```sh
> echo '$(task --list)'
$(task --list)
```

Using double quotes is already enough to stop any further interpolation of the string coming back from the subshell because the returned string will be escaped. You can illustrate this by running:
```sh
printf "%q" "$(task --list)"
```
The printed string will contain escape sequences (such as `\n` or `\$`).

**Comment by mrhillsman** [comment]
@bergercookie here you go great follow up explanation from @pd93 hth

**Comment by bergercookie** [comment]
Thank you both!
This makes total sense :)
