### ISSUE TITLE
Prompt attribute is not working

### ISSUE THREAD

**Issue by liiight** [go-task/task#1209]
Task `prompt` attribute does not trigger a prompt

```
❯ cat <<EOF > Taskfile-test.yml
version: '3'
tasks:
  default:
    prompt: prompt test
    cmds:
      - echo "no prompt"
EOF
❯ task -t Taskfile-test.yml
task: [default] echo "no prompt"
no prompt
❯ task --version
Task version: v3.25.0 (h1:XtIEtWpQSbIf2FGU+44/QB1whFf2sBUB/02W7ZQSz0U=)
```
- Task version: v3.25.0 
- Operating system: MacOS 13.4
- Experiments enabled: No

**Comment by andreynering** [comment]
Hi @liiight,

That feature wasn't released yet. [See](https://github.com/go-task/task/blob/44aaec86a10dfac0871d677563ff5e80890f46ad/CHANGELOG.md). If you build Task from source you'll have it.

Our website builds from the `main` branch, that's why you see the documentation for it. We may improve that in the future. Sorry for the confusion.

**Comment by liiight** [comment]
I see. Thanks for the quick response!
I get it, docs are a pain to maintain and be as informative as needed.

Thanks for your work on this awesome project! Looking forward to the next release.
