### ISSUE TITLE
if .env is not a file, the program panics

### ISSUE THREAD

**Issue by lu911** [go-task/task#1244]
- Task version: 3.27.0
- Operating system: mac os 13.1
- Experiments enabled: no

This is the error statement when Task CLI is executed `panic: read .env: is a directory`

I have an .env directory in a project I'm working on. In go-task 3.27.0 version, go-task expects .env to be a file not a directory, so the presence of a directory with the name .env causes panic.

**Comment by erickim713** [comment]
I have a same issue too..

**Comment by pd93** [comment]
@lu911 Thanks for the report. #1245 should fix this.

@andreynering a hotfix for this might be a good idea seeing as its causing a panic. I've also noticed that since we changed the dotenv loader to load during `init()`, that we are not able to grab the taskfile directory, so the `.env` containing experiments is always being loaded from the user's CWD instead. Not sure if this is desired or not.

**Comment by andreynering** [comment]
> I've also noticed that since we changed the dotenv loader to load during init(), that we are not able to grab the Taskfile directory, so any .env containing experiments is always being loaded from the user's CWD instead. Not sure if this is desired or not.

@pd93 Ideally, it should read from the Taskfile directory.

**Comment by lu911** [comment]
Thanks! :D
