### ISSUE TITLE
invalid version: unknown revision 3.27.1

### ISSUE THREAD

**Issue by PaluMacil** [go-task/task#1247]
- Task version: 3.27.1
- Operating system: Windows and Ubuntu
- Experiments enabled: N/A

I tried to install the latest release with `go install github.com/go-task/task/v3/cmd/task@3.27.1` on Windows and Ubuntu, getting:
> go: github.com/go-task/task/v3/cmd/task@3.27.1: github.com/go-task/task/v3/cmd/task@3.27.1: invalid version: unknown revision 3.27.1

When I go to https://pkg.go.dev/github.com/go-task/task/v3 it shows 3.27.1 as latest. I finally tried `go install github.com/go-task/task/v3/cmd/task@v3.27.1` (note the v in the tag). I'm not even sure why I tried that since I've never used a v in the version. It worked, so I'm not blocked on anything I'm doing, but this seems like it will be terribly confusing for new users and could use a new release. Unfortunately, I don't have a clue what could cause this. I compared to another repo and didn't find anything unusual.

**Comment by pd93** [comment]
I'm a little confused as to what the problem is here. 

> I'm not even sure why I tried that since I've never used a v in the version

`go install`ing a specific version has always required you to specify `@latest` or `@v...`. Previous releases of Task have always required the `v` prefix too. This is just [how the Go tool works](https://pkg.go.dev/cmd/go#hdr-Compile_and_install_packages_and_dependencies).

> When I go to https://pkg.go.dev/github.com/go-task/task/v3 it shows 3.27.1 as latest.

It shows `v3.27.1` - Note the `v` prefix:
![image](https://github.com/go-task/task/assets/9294862/35195bc2-409d-454f-ad81-a53890005fb5)

Some examples of other popular binaries written in Go that work the same way:

- `go install github.com/gohugoio/hugo@v0.115.0`
- `go install github.com/FiloSottile/mkcert@v1.4.1`
- `go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.52.2`

If I try any of these without the `v` prefix, they will fail.

Also, worth noting as-per [our docs](https://taskfile.dev/installation/#build-from-source), that you can always install the latest version by using `go install github.com/go-task/task/v3/cmd/task@latest`
