### ISSUE TITLE
Website (taskfile.dev) is down

### ISSUE THREAD

**Issue by ambis** [go-task/task#1311]
https://downforeveryoneorjustme.com/taskfile.dev

It's not just you! [taskfile.dev](http://taskfile.dev/) is down.

Last updated: Aug 23, 2023, 1:33 PM (1 second ago)

**Comment by sbocinec** [comment]
It's down for us also, as a temporary workaround to install the task file we use:
`curl --location https://raw.githubusercontent.com/go-task/task/main/docs/static/install.sh`

**Comment by andreynering** [comment]
I'm sorry for the trouble. I migrated the domain away from Google Domains because it was bought by another company.

I have transferred all DNS rules. Not sure if this can be a cache issue. Sometimes DNS takes some time to propagate. For me it's working correctly here, for example.

I'll keep my eyes on it.

**Comment by andreynering** [comment]
Everything is fixed now. Sorry again for the inconvenience.
