### ISSUE TITLE
Breaking changes in v3, taskfile/read pkg removed

### ISSUE THREAD

**Issue by titpetric** [go-task/task#1958]
Previously a taskfile/read package was provided, which i imported and used for taskfile. This API isn't available today anymore, and a v4 is not tagged.

**Comment by pd93** [comment]
Unfortunately, our package API is not currently stable and does not guarantee backwards compatibility. While we generally avoid breaking it on purpose, the CLI is our priority and if a change is made easier by breaking the package API, then we have/will do so. 

In the specific case of `taskfile/read`. This was mostly just a package rename in an effort to improve the intuitiveness of the API surface (`read` is not a good package name IMO). When updating to the latest version of Task, you should be able to import `github.com/go-task/task/v3/taskfile` instead and get the same functions. The package for handling the schema/AST directly is now in `github.com/go-task/task/v3/taskfile/ast`.

It is possible that we may stabilise the package API in the future and this has been discussed a few times (e.g. #121). However, this has not been done in the past because we did not feel it was in a good enough state to do so.

I do think we should consider a section in our documentation where we describe how to use Task as package with explicit warnings about the lack of stability.
