### ISSUE TITLE
Remove the vendor/ directory on v3 once the lasts 2 Go versions have modules enabled by default

### ISSUE THREAD

**Issue by marco-m** [go-task/task#214]
While trying to add Windows build support to Travis, I _think_ I stumbled upon the interaction between Travis, Go modules and vendoring (https://arslan.io/2018/08/26/using-go-modules-with-vendor-support-on-travis-ci/).

Then I asked myself: before going down a rabbit hole, since the project has Go module support, is there a need to keep the vendor directory around ?

**Comment by andreynering** [comment]
Hi @marco-m,

The vendor directory is there are because there're probably people out there that still installs Task by running `go get github.com/go-task/task/cmd/task`.

To have an idea, here's the clone graph for the past week:

<img width="761" alt="Screen Shot 2019-06-16 at 11 05 52" src="https://user-images.githubusercontent.com/7011819/59565239-14498e80-9027-11e9-8fbb-4371ca19be0b.png">

We don't know how many of these cloners are using plan `go get` vs. Go modules, though.

Deleting the `vendor` directory will possibly break stuff for those who still use `go get`, since `go get` always downloads the latest version of dependencies AFAIK.

I *do* plan to delete it at some point, though.

**Comment by marco-m** [comment]
Ah, I didn't know about this `go get` behavior. If I find some time, I want to dig into it to understand better.
Thanks for the explanation, although it seems to make Windows on Travis more difficult (yes, I read your answer about using AppVeyor instead). As an aside, I really don't like the "magic" that Travis does for Go, modules or GOPATH.

**Comment by andreynering** [comment]
OK, I think we can do this once the lasts 2 Go major versions have modules enabled by default.

I think that will be the case once Task v3 is release.

**Comment by andreynering** [comment]
Done on 49bf395f61275977e0c3bdd0403da35a5ff4dd25
