### ISSUE TITLE
[Feature Request] Private tasks

### ISSUE THREAD

**Issue by JulienBreux** [go-task/task#284]
It's possible to have private task ?

Definition of private task:
- Only callable inside a Taskfile
- Never listed outside with `task -l`

Thanks 🙏

**Comment by andreynering** [comment]
Hi @JulienBreux,

Tasks without a `desc:` are kinda private, since they won't be listed on `task -l`.

It'd be trivial to allow `private: true` in a task, but the benefit is relatively small. I'm open for opinions.

**Comment by BnGx** [comment]
The idea of ​​a _private_ task seems interesting to me because it could be reserved for advanced users or automatic actions like Git hooks.

For example, if there are a series of tasks such as formatting or linting of the code, it would be appropriate to hide them from the task list but still recall them from the cli.

The list of tasks could become very long for complex projects, confusing the developer who normally focuses on productivity during the development phase using canonical tasks such as _test_, _run_, _docs_.

**Comment by pd93** [comment]
@BnGx See [internal tasks](https://taskfile.dev/usage/#internal-tasks).

**Comment by BnGx** [comment]
I know the internal tasks, however these are not callable from the CLI and have a different purpose than what I described.
