### ISSUE TITLE
Search for Taskfiles in parent directories

### ISSUE THREAD

**Issue by Chi-teck** [go-task/task#289]
Is it possible to run Task commands from child directories without specifying a path to the Taskfile explicitly (`task -t ../.././Taskfile.yml`)?

**Comment by andreynering** [comment]
Hi @Chi-teck, and thanks for opening this issue!

This is a good idea indeed: searching for parent directories if a Taskfile isn't found in the current one.

I plan to work on this eventually, but contributions are also welcome.

**Comment by Chi-teck** [comment]
The most noticeable example of such feature is Git. You don't have to cd to project root repository to execute Git commands.

**Comment by Chi-teck** [comment]
Meanwhile the following Bash function can be used as a workaround.
```
#
# Task wrapper that searches for task file recursively.
#
function task {

  # Do not proceed if '--taskfile' option was supplied.
  for i in "$@"; do
    if [[ $i == -t* || $i == --taskfile=* ]]; then
      command task "$@"
      return $?
    fi
  done

  local DIR=$(pwd)
  while true; do
    if [[ $DIR == '/' ]]; then
      command task "$@"
      return $?
    fi

    if [[ -f $DIR/Taskfile.yml ]]; then
      command task --taskfile="$DIR"/Taskfile.yml "$@"
      return $?
    fi

    DIR=$(dirname "$DIR")
  done
}

```

**Comment by stephencheng** [comment]
@Chi-teck you may want to try it out: https://github.com/upcmd/up, it support dynamically load the task file.

docs here: https://upcmd.netlify.app/usage/config_yml/ use refdir

**Comment by marco-m** [comment]
Another example of tool that has this behavior is the scons build tool, see the `-u` or `--up` flag in the scons man page https://scons.org/doc/production/HTML/scons-man.html.

**Comment by ibes** [comment]
Would there be a way - similar to the bash file - where I can tell for my project to always attach my project taskfile in the command?

Hm - likely the flaw on this way is, that the bash command needs to be global or can only be used by on project. 
As otherwise: How does the script know if it is supposed to do stuff. 

There could be a config file for the bash script.

If somewhere within this path (=project), add taskfile config x
If somewhere within this path (=project), add taskfile config y

Not sure if that really is a solution, but maybe it's easy enough.

Would love to see this feature.
Unfortunately I am not skilled to contribute.

**Comment by marco-m** [comment]
Nice one! Thanks!
