### ISSUE TITLE
Compile as a binary

### ISSUE THREAD

**Issue by soullivaneuh** [go-task/task#296]
Go-task is very useful to create smart commands with ease, but you always have to bring a Taskfile to make it running.

It would be a nice addition to have a compilation option to have a portable binary at the end.

**Comment by tommyalatalo** [comment]
Personally I think this feels like a really bad idea since you will have no way to gain insight as to what the tasks are actually doing, and no way to update them. It's a real benefit to have transparency into the Taskfiles which also makes them easy to maintain and fix in case of errors.

No, a compiled task runner binary seems like a black box of horrors to be honest.

**Comment by andreynering** [comment]
Hi @soullivaneuh,

Perhaps once #121 is addressed it would be possible for a third-party project to generate a binary for a Taskfile, but I don't plan to implement that on Task itself.
