### ISSUE TITLE
Feature request: .env support

### ISSUE THREAD

**Issue by chris-garrett** [go-task/task#324]
Hiya, 

I have quite a few projects that use .env files for configuration. Docker, Node, Java, .Net and Go. I would like to port these projects from rake to task. Is there any interest in having that in this code base? If so I will open a PR. 

Thanks,

**Comment by andreynering** [comment]
Hi @chris-garrett,

This sound reasonable. I think we should probably have a global configuration for this, though:

```yaml
dotenv: [.env, .customdovendfilename.env]
```

This way we both allow custom file names and prevent some confusion regarding envs being imported automatically (I think we shouldn't even import he default `.env` file unless specified in the Taskfile).

Also, if you plan to work on this, please use `v3` as the base branch instead of `master`.

**Comment by chris-garrett** [comment]
> This way we both allow custom file names and prevent some confusion regarding envs being imported automatically

That's a good idea. 

> Also, if you plan to work on this, please use v3 as the base branch instead of master.

Sounds good.

**Comment by stephencheng** [comment]
@chris-garrett I have just released a feature in https://github.com/upcmd/up to fully manage env vars and associate pipeline env vars with the execution of a task

details here: https://github.com/upcmd/up/issues/3

For your case, if you want to use .env file, you will just need to reference to that file

You might want to try it, it is designed for that purpose

**Comment by chris-garrett** [comment]
I will check that out when I pick this up again. ETA is a few weeks. Thx.

**Comment by andreynering** [comment]
Done on #356, closing this issue...
