### ISSUE TITLE
Shell is evaluated even before running the task

### ISSUE THREAD

**Issue by ronlut** [go-task/task#332]
- Task version: `v3.0.0-preview3`
- OS: mac

Hi, thanks for the great work!
Task v3 evaluates shell commands before running the task - for example when running `task --list`.
This is not the behaviour in v2 and doesn't make sense as a lot of tasks depend on previous tasks.

Example:
```
version: '3'

tasks:
  foo:
    desc: foo
    cmds:
      - echo $MSG
    env:
      MSG: {sh: 'sleep 10; echo hi'}
```

Running `task --list` will sleep for 10 seconds.
In v2 it will just work as expected :)

Same bug occurs under `vars: ` so I guess it has to do with the shell evaluation.
If you point me into a direction that might cause this behaviour I can add a PR to fix it.
Thanks!

**Comment by andreynering** [comment]
Hi @ronlut,

It's possible that the behavior is completely different in the `v3` branch currently as it was refactored a few days ago (and not yet released on the `preview` channel). It'd be nice if you could try it.

Or if you don't want to build from source, I plan to release the last v3 preview release soon (before it goes to stable).

**Comment by nwb-rony** [comment]
Checked with latest commit on v3 branch - bug still exists.

**Comment by ronlut** [comment]
Checked with latest commit on v3 branch - bug still exists.

**Comment by andreynering** [comment]
Hi @ronlut,

I just figured out what's happening. Actually this is not a v3 issue, it's also on v2, but only starting on the v2.8.1 release, which was made later in the same day you opened this issue.

This was caused by #276 and #283, i.e. someone couldn't use variables on `desc` before this patch.

To be honest, I'm not sure about what to do here. That a valid feature request, but comes with this drawback of making stuff slow if you have slow dynamic variables (which people should usually avoid if possible).

**Comment by nwb-rony** [comment]
Hi, thanks for the reply.
I don't think it's only a problem with slow variables.
It may fail `task --list` in various scenarios. If you use vars somewhere in the shell it will fail as when running `task --list` you don't provide any vars - you just want to know what tasks are available.

**Comment by ronlut** [comment]
Hi, thanks for the reply.
I don't think it's only a problem with slow variables.
It may fail task --list in various scenarios. If you use vars somewhere in the shell it will fail as when running task --list you don't provide any vars - you just want to know what tasks are available.

**Comment by andreynering** [comment]
Perhaps we should skip errors on variables when using `--list` and just print a blank string

We could also set a timeout for these shell when on `--list` (1 second? 0.5?)

**Comment by mihi314** [comment]
Shell tab-completion is also affected by this. Which can make it unusably slow, or even not work at all when a command fails.

**Comment by rmmcnulty9** [comment]
Any updates on this? This seems like a pretty big regression to have in the code base for so many releases.

**Comment by andreynering** [comment]
Now in master, interpolation still work for `desc` but dynamic variables will not run at all for `--summary` and `--list` flags. I hope this is a good trade off.

**Comment by b4nst** [comment]
@andreynering I understand why we don't want dynamic variables being computed for `--summary` and `--list` but could they be at least redacted with something like `<runtime-computed>` because right now with this Taskfile:

```yaml
version: '3'

vars:
  PROJECT_VERSION:
    sh: git describe --tags --always
    
tasks:
  echo:
    desc: Test task
    summary: |
      Echo '{{.PROJECT_VERSION}}'
    cmds:
      - echo {{.PROJECT_VERSION}}
```

We ends up with:
```
➜  task --summary echo                                                                                                                                                                                                                                                    10:48:54
task: echo

Echo ''

commands:
 - echo
 ```
 
Which is a bit misleading

**Comment by andreynering** [comment]
@b4nst If you think this is important, please open another issue about it.

Comments in closed issues tend to be forgotten.

**Comment by Zebradil** [comment]
I have a use case in which interpolation in `summary` would be quite helpful.

I often use Taskfile as an interface to run shell scripts, which might require arguments or environment variables set. Requirements are usually described in a script's help/usage message. However, I can't provide it natively in a `summary` when a Taskfile is used instead of using the script directly. This leads to an inconvenience when a help message should be changed — it has to be changed in several places.

Would it be an option to have a way to inject dynamic variables into `summary`?
