### ISSUE TITLE
(feat): import vars

### ISSUE THREAD

**Issue by lukasmrtvy** [go-task/task#353]
I am aware of importing taskfiles, but it would be nice to have similar behaviour for importing taskvars yaml ( it should be possible to reference different file name )

```
version: '2'

import_vars:
  - myvars.yaml
vars:
  foo: bar

tasks:
```

Related: https://github.com/go-task/task/issues/98

**Comment by andreynering** [comment]
Hi @lukasmrtvy, thanks for opening this issue!

I'm closing this because this proposes something that's going in the opposite direction on what's currently planned.

On v2 (current stable release) there's `Taskvars.yml`, which's imported automatically and you can add vars, but it'll be removed on v3.

That was duplicated functionality, since you can have variables on imported Taskfiles, too:

```yaml
version: '3'

vars:
  # ...
```
