### ISSUE TITLE
Support lowercase(taskfile) & yaml extension (i.e., {Taskfile,taskfile}.{yaml,yml})

### ISSUE THREAD

**Issue by kkweon** [go-task/task#369]
Hello. I'd like to contribute but want to ask first. 

The rationales are

1. Not all filesystems are case sensitive.
2. **yaml** is preferred extension to **yml** (https://yaml.org/faq.html)

Hence, I propose the default should be `taskfile.yaml` and all other variations should be supported.

`{Taskfile,taskfile}.{yaml,yml}`

**Comment by andreynering** [comment]
Hi @kkweon,

This suggestion came before, and I already decided against this.

This would raise the code complexity a bit for almost no benefit.

I kinda like the enforcement of `Taskfile.yml` because that means consistency across the community.

**Comment by tomarrell** [comment]
This is quite unfortunate, we have a fair number of `yaml` files in our codebase, defining things such as Kube resources, and having a `Taskfile.yml` makes our codebase internally inconsistent with something as simple as just the file extension. We're also not willing to go against the standard of using `yaml`, as it is likely muscle memory for the majority.

I would strongly advocate for supporting both extensions under the premise that consistency within the same codebase is more important than consistency across the community. Especially with something as relatively trivial as a file extension.

**Comment by pd93** [comment]
I would like to add that in addition to @tomarrell's points, this request in itself is a standard feature across the wider developer community. Both `makefile` and `dockerfile` are acceptable filenames despite their "standard" filenames being capitalised. This is supposed to be a drop-in replacement for a `makefile`, but it does not have feature parity in this respect.

> for almost no benefit

As trivial as this change is, and despite the lack of functional benefits, some of us developers are a bit protective of our own preferences (tabs/spaces, curly braces on new lines etc.) and I see this as a stumbling block to adoption if someone doesn't like the way a tool does something so core to its usage. This is a big shame for me because I really like the premise of the tool and would like to adopt it on future projects. It just kind of sucks that it would stand out as the only file in the root of my project with a capitalised file name.

I hope if this issue gets enough attention, you'll maybe reconsider, or at least explain what the additional complexities required to add this feature are and why they outweigh the benefits of implementing it.

**Comment by andreynering** [comment]
FYI: We are about to allow `.yaml` as extension soon as part of #584 and #621.
