### ISSUE TITLE
Task file commands with template range don't fail

### ISSUE THREAD

**Issue by tdakkota** [go-task/task#403]
Task version:
```
$ task --version
Task version: 3.0.0
```

File to reproduce:
```yaml
# https://taskfile.dev

version: '3'

vars:
  PACKAGES: | 
    alg
    iterator
    cache
    constraints
    list
    slices
    trees
    testutil

tasks:
  translate:
    cmds:
      - cmd : |
          {{range $i, $line := .PACKAGES | splitLines }}{{ if $line -}} 
          {{ if eq $i 5 }}exit 1 
          {{ end -}} 
          exit 0
          {{ end }}{{ end -}}
```

Task output:
```
$ task translate
task: exit 0
exit 0
exit 0
exit 0
exit 0
exit 1 
exit 0
exit 0
exit 0
```

**Comment by andreynering** [comment]
Hi @tdakkota, thanks for reporting this issue!

What happened is that [the Shell library that Task uses](https://github.com/mvdan/sh) does not automatically fail commands unless they are the last command in the string.

Adding `set -e` to the top of your command would have fixed this issue. But seems failing is the expected behavior, I just pushed a fix and that will be done automatically starting in the next release. See ac8e3441736a9cab4c64f8feb67619bfda17a08a.
