### ISSUE TITLE
Rename ARM releases

### ISSUE THREAD

**Issue by thetillhoff** [go-task/task#478]
- Task version: new ones
- Operating System: Raspberry Pi OS

The github release-filenames contain their respective architecture. Is there a reason why for ARM it is just `arm` and not `armhf`?
IMO this would make it scriptable via `$(dpkg --print-architecture)`.
Or am I missing something here?

**Comment by andreynering** [comment]
Hi @thetillhoff,

There's really no reason on why it's named as is other that `arm` it's what [Goreleaser](https://github.com/goreleaser/goreleaser) generates by default.

Changing it now wouldn't be nice because it'd breaking existing scripts (and lots of people download these release in an automated way).
