### ISSUE TITLE
Not Working with Subshells

### ISSUE THREAD

**Issue by ProfessorManhattan** [go-task/task#526]
- Task version: 3.4.3
- Operating System: Big Sur

### Example Taskfile showing the issue

```yaml
  update-files:
    deps:
      - npm-hbs
    cmds:
      - |
        find ./.common/files-\{{.REPOSITORY_SUBTYPE}} -type f | while read FILE; do
          if [ "${FILE##*.}" == 'handlebars' ]; then
            FILE_BASENAME=$(basename $FILE)
            hbs --data .variables.json "$FILE" --stdout > "$(dirname $FILE)/${FILE_BASENAME%.*}"
          fi
        done
```

I have noticed that Task does not handle subshells well if at all. Any time I try to use something with $(), I see strange behavior. I have been able to get around this by using `env:` and `vars:` but I cannot always do that. In the example above you can see that there is a loop/if statement. In this case I cannot leverage `env:` or `vars:` because the code depends on information only available in the loop/if statement.

Questions:

* How should we handle scenarios where subshells are necessary?
* Is there a way to loop a `- task: taskname` command?

**Comment by andreynering** [comment]
Hi @ProfessorManhattan,

Since this is a shell issue, it'd be useful if you could reproduce the limitations on one or more minimal `.sh` files. This way we could be sure that it works on regular shell but not on the library. [There's a command line tool you could install to run to shell file directly using the library](https://github.com/mvdan/sh/blob/master/cmd/gosh/main.go):

```shell
env GO111MODULE=on go get mvdan.cc/sh/v3/cmd/gosh
```

If you manage to do it, could you please open another issue [on this repo](https://github.com/mvdan/sh/issues/new) about it? We can still keep this one open for a while to track the progress...

**Comment by ProfessorManhattan** [comment]
Hey @andreynering -- I have noticed that anytime you run anything in inside a `$()` it fails to run. There are ways of getting around that issue with subtasks but the main issue I'm facing right now is the lack of ability to run a script in the context of the terminal session that ran the original `task` command.

For instance, with a shell script that looks like this:

```
#!/bin/usr/env bash

read "HEYYO"
```

Task will never even prompt for the user's input since it's running in a background subshell somewhere. Ideally, we should have the ability to run scripts on the main shell, similar to how you can run scripts defined in `package.json` with NPM.

I would like to see this issue addressed so much that I tried hiring a Go developer on Upwork to add the feature/create a PR but Go developers are not as easy to find as I would like.

**Comment by ProfessorManhattan** [comment]
The sub shell issue that I opened this with seems to be fixed in the latest release. Closing..
