### ISSUE TITLE
This doesn't print both env variables

### ISSUE THREAD

**Issue by bucknerns** [go-task/task#586]
- Task version: v3.9.0 (h1:k6ZHDqKU+NCJxN2PhHRB4gF0NSZVlRdRSbtP89pDKDA=)
- Operating System: Ubuntu 20.04

### Example Taskfile showing the issue

```version: '3'

env:
  GREETING: Hey, there!
  GREETING2: Hey, there2!

tasks:
  greet:
    cmds:
      - echo $GREETING $GREETING2
```

**Comment by jespino** [comment]
This bug is not strictly related to the task project, is an upstream bug in the `https://github.com/mvdan/sh` repository. The problem is whit the `ListEnviron` object, that is not working fine with this cases (the internal sort + the binary search are conflicting somehow). The solution is to fix the problem in the upstream or add another environment store implementation locally (that is an interface, so is doable).
