### ISSUE TITLE
Read Taskfile from stdin

### ISSUE THREAD

**Issue by dAnjou** [go-task/task#655]
Hi, it'd be cool to do something like this:

```bash
generate_taskfile.sh | task --taskfile - lorem
```

**Comment by mgbowman** [comment]
I also tried with file pipe redirection 😞 
```
task -t <(cat ~/shared/Taskfile.yaml)
task: No Taskfile found in "/dev/fd/12". Use "task --init" to create a new one
```

I'm interested in this for a _remote_ `rtask` shell alias...
```
alias rtask='task -t <(curl ...)'
alias rtask='curl ... | task -t -'
```

**Comment by ghostsquad** [comment]
bump. This is needed. I'm dynamically generating taskfiles, and it would be nice if I didn't have to write it to disk first.

**Comment by pd93** [comment]
This was pretty low-hanging fruit now that we have the `Node` interface. See #1483. Feedback very welcome if you have the time to test before it is merged.

**Comment by pd93** [comment]
> It might be that a 1 line change there at the `IsRegular()` check could do the trick, to just be more permissive than only "regular" files, and instead permit any file that's compatible with `os.Open()` and `io.ReadAll()`

@brianbraunstein I think we only really want to add `ModeDevice` to the list? I would like this check to be as restrictive as possible unless we have a specific reason to allow more modes. ([Full list of modes here](https://github.com/golang/go/blob/cf52e709977d331a70df9463cf9e307024b6779f/src/io/fs/fs.go#L181-L193)). Please feel free to suggest other modes you think are necessary and why.

>   Is it necessary to disallow `-d` and `-t` ?  It seems like if you're doing`-t <(foo)` or `-t /dev/stdin` that you may want to change the directory too, but I guess you can always just `(cd somewhere; task -t <(foo)`

It is not necessary no. However, there is a surprising amount of internal work required in order to do this in a way that is both backwards compatible and maintains the expected behaviour. This functionality is also required for #1347 to work correctly and as such, I have been working on it over there instead of here.
