### ISSUE TITLE
Rename homebrew binary

### ISSUE THREAD

**Issue by CaptainQuirk** [go-task/task#697]
Hi there,

I would like to install go-task on my Linux distro with homebrew but unfortunately, there is already a built-in Formula named `task` in **homebrew-core** for [taskwarrior](https://github.com/GothenburgBitFactory/taskwarrior) that I happen to use.

Since the latter is quite more ancient than go-task, would you consider renaming the binary in your homebrew tap ?

Thanks in advance !

**Comment by ghostsquad** [comment]
I agree that a different name should be used. Until that happens, here are some options:

Use `asdf` to manage go-task, and brew for taskwarrior.

Depending on how your path is setup (such as if brew is first), you could then just use a local alias, e.g.

```
alias gotask=$HOME/asdf/shims/task
```

If you want brew at the end of your Path, or if you want to be more explicit, you can setup

`wtask` and `gtask` aliases or symlinks.

Here's more information
https://ofstack.com/Linux/34143/correct-usage-of-homebrew-in-linux.html

I'll have to look more into homebrew to see what kinds of issues we would run into by renaming things.

**Comment by andreynering** [comment]
I think renaming probably wouldn't be good idea because of backwards compatibility, and also consistency (with other release methods).

If we rename it, everybody that is already used to type `task` will be confused on why it's suddenly not working anymore.

Also, this conflict is not exclusive to Homebrew, but affects everything else: Snap, Linux package managers, and even the binaries themselves.

**Comment by ghostsquad** [comment]
@andreynering can we publish a second bottle with a different name? or create a tap?

I feel like this is release overhead, but if it helps someone maintain 2 binaries at the same time with the same name, seems like it's worth it. I know I've run into this problem too.

Personally, [go]task is more important than taskwarrior, so I use ASDF to manage that dependency, it helps ensure that it's documented and available in my projects/repos via the `.tool-versions` file. My ASDF path takes precedence over brew.

So I have a separate alias to access taskwarrior, as `tw`.

@CaptainQuirk this may not be an ideal answer for you, but this is not the only binary in the history of binaries that has a conflict in brew.

I'm not sure if there's another way to specifically manage the binary [re]name in brew, but I do know that both binaries have several install methods.

**Comment by 4x0v7** [comment]
What about calling it `taskfile`? That's how I remember `task` , as `taskfile.dev` since I reference the docs frequently.

It also has an immediate familiarity with users of `make` and a `makefile`

**Comment by ghostsquad** [comment]
I have tried `asdf-alias` but you can also just make an alias in your .bashrc or .zshrc.

**Comment by ghostsquad** [comment]
@CaptainQuirk given that we won't be renaming the brew bottle/tap, I'll be closing this issue. It's a bit out of scope to discuss how to manage multiple binaries of the same name via `PATH` and aliases here. I hope that I was at least able to provide a bit of help and direction though to resolve this issue. Thank you for your understanding!

**Comment by CaptainQuirk** [comment]
I successfully dowloaded the binary and installed it as go-task manually which is fine by me !

**Comment by thoroc** [comment]
> @CaptainQuirk given that we won't be renaming the brew bottle/tap, I'll be closing this issue. It's a bit out of scope to discuss how to manage multiple binaries of the same name via `PATH` and aliases here. I hope that I was at least able to provide a bit of help and direction though to resolve this issue. Thank you for your understanding!

Given that you provide a homebrew recipe that conflict with pre-existing one, you will find other people that will not use it, making your effort worthless. I would respectfully encourage you to either remove that recipe or fix the conflict.

**Comment by C0rn3j** [comment]
@andreynering
> I think renaming probably wouldn't be good idea because of backwards compatibility, and also consistency (with other release methods).

At this point, it's consistently broken everywhere.

On Arch Linux User repo, the packagers have also renamed `task` binary to `go-task` due to taskwarrior conflicts.

https://aur.archlinux.org/packages?O=0&SeB=nd&K=go-task&outdated=&SB=p&SO=d&PP=50&submit=Go

For backwards compatibility and consistency, would shipping a binary + symlink to `task` not be a good solution?

In a few months/years/releases when it is deemed that community no longer should be using `task`, one can then remove the symlink when everyone has accustomed to using the new naming, only leaving the renamed binary.

**Comment by ghostsquad** [comment]
@C0rn3j this is a well written comment. It only address a subset of people though:

Those that use taskwarrior and task through the same package manager.

Where would the symlink be installed? I don't quite understand how this is backwards compatible.

There are other ways to maintain/install either binary.

Can you help me understand the finer details of this proposal?

**Comment by C0rn3j** [comment]
> Can you help me understand the finer details of this proposal?

Currently, ignoring other things, binary is installed as /usr/bin/task on Linux.

This will be renamed to `/usr/bin/taskfile` (or `go-task`, or whatever name is settled on), and symlink will be made with `/usr/bin/task` ponting to `/usr/bin/taskfile`.

Documentation will be changed to reflect this, warnings will be put in that it is now not `task` but `taskfile` and that `task` will not work in the future time.

Then after some time, probably in a major release like 4.0 to denote the breaking change, task will ship without the symlink, leaving only `/usr/bin/taskfile` on the system. 

Users will have had ample time to migrate by then and this should cause minimal to no upset.

**Comment by ghostsquad** [comment]
I support this. @andreynering ?

**Comment by trallnag** [comment]
@ghostsquad maybe reopen this issue as it still seems to be in discussion by collaborators (you)

**Comment by pd93** [comment]
@trallnag I think this is very unlikely to happen. It would cause problems for far more people than it will benefit. The number of users using both binaries is very small.

See [this poll](https://discord.com/channels/974121106208354339/974121106984304692/1036284261390635018) and [this conversation](https://discord.com/channels/974121106208354339/974121514184085555/1036280840054919178) on Discord for previous discussions. I think a far more likely direction is that we document how people can work around the problem with a small guide in the docs.

**Comment by trallnag** [comment]
Okay, thanks for the pointers

**Comment by nikolay-turpitko** [comment]
https://github.com/Homebrew/homebrew-core/issues/119921

**Comment by C0rn3j** [comment]
@pd93 

Arch has broken completions - https://gitlab.archlinux.org/archlinux/packaging/packages/go-task/-/issues/1#note_145186

Brew has broken completions - https://github.com/Homebrew/homebrew-core/issues/119921#issuecomment-1374714077

I still think my proposal here https://github.com/go-task/task/issues/697#issuecomment-1223748235 would be the way to go for a long-term solution, instead of having every downstream maintainer inherit issues stemming from keeping the status quo.
