### ISSUE TITLE
What happened to 3.12 release?

### ISSUE THREAD

**Issue by ghostsquad** [go-task/task#723]
The 3.12 release has disappeared, breaking builds for me.

**Comment by per1234** [comment]
It is still here: https://github.com/go-task/task/releases/tag/v3.12.0
and here: https://github.com/go-task/task/tags

but not listed here: https://github.com/go-task/task/releases

The Releases page shows only GitHub releases when there has been at least one in the repository, so that is the behavior I expect when a tag is created without making a release for it, but https://github.com/go-task/task/releases/tag/v3.12.0 has custom release notes, assets, reactions so it must be a GitHub release.

What exact breakage are you experiencing @ghostsquad? I am able to use the tag in Git commands:

```text
$ git clone -b v3.12.0 https://github.com/go-task/task
```

**Comment by andreynering** [comment]
Looks like a bug in GitHub. It's showing v3.11.0 as the latest, but I don't know why.

![Screen Shot 2022-05-10 at 17 54 27](https://user-images.githubusercontent.com/7011819/167720246-8f32be85-4c2d-460e-9ff8-9a06e94b072d.png)

**Comment by andreynering** [comment]
This got with with the brand new v3.12.1: https://github.com/go-task/task/releases/tag/v3.12.1

**Comment by ghostsquad** [comment]
Thank you. I use ASDF to install task, which looks at the GitHub releases. So it wasn't listing 3.12 any more. I'll have to see if I can find more information about this GitHub bug.

Thanks for publishing 3.12.1
