### ISSUE TITLE
Install script is not preperly detecting the ARM v7 architecture

### ISSUE THREAD

**Issue by varac** [go-task/task#842]
Currently, Taskfile doesn't install on RPi 4 (armv7):

```
pi@pi:~ $ sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d
go-task/task crit platform linux/armv7 is not supported.  Make sure this script is up-to-date and file request at https://github.com/go-task/task/issues/new
```

Please provide armv7 binaries.

**Comment by andreynering** [comment]
Hi @varac,

Does the binary work in your machine if you download `task_linux_arm.tar.gz` from the [releases page](https://github.com/go-task/task/releases)?

I'm trying to understand if the problem is the binary or just the download script.

We use v6 for ARM binaries which is the default on Goreleaser.

**Comment by varac** [comment]
I just tried the latest `task_linux_arm.tar.gz ` on a `Raspberry Pi 4 Model B Rev 1.1` (armv7l) and it works.
So it must be an issue with the installer script.
