### ISSUE TITLE
Bash completion: _init_completion: command not found

### ISSUE THREAD

**Issue by jfwilkus** [go-task/task#862]
- Task version: v3.15.0 from homebrew tap
- Operating System: macOS 12.5.1
- Bash: 5.1.16

It seems after the upgrade to 3.15.0 from 3.14.1, bash-completion is not working and I get the following error message after I hit tab to autocomplete tasks.

```bash
task <tab> bash: _init_completion: command not found
```

**Comment by MarioSchwalbe** [comment]
Yes and no. It is true I used another initialization function `_init_completion` instead of the previous one. However, since I'm on Mac OS as well, I can confirm this is working. The function is defined in `/usr/local/share/bash-completion/bash_completion` line 728 (provided by the package `bash-completion@2`), but the completion framework must be loaded first.

@jfwilkus: Are you using the old version for bash 3.2 (Homebrew package `bash-completion`)?

**Comment by jfwilkus** [comment]
@MarioSchwalbe Yes, I was using the old version. Just upgraded to `bash-completion@2` and all is working now. 

Thanks for the quick responses!
