### ISSUE TITLE
Suggestion: Publish task as an npm package

### ISSUE THREAD

**Issue by ath88** [go-task/task#870]
Hello there,

We have several node.js projects where we would love to use task as our task runner. But - that would require every developer to install task on their local development host. Usually we include development dependencies in the `package.json`-file of our projects. There are tools we can't install this way, such as docker, but it'll be an easier sell in the team if we can just add it into our existing dependency list.

There are tools that makes it easy to publish go binaries to npm packages while still handling cross-platform issues, such as https://github.com/sanathkr/go-npm. 

Would you be open to do this?

**Comment by andreynering** [comment]
Hi @ath88,

I liked the idea, so I just gave it a try and it seems to be very simple indeed, so I'll commit to do that.

I opened a PR with the WIP work on it: https://github.com/go-task/task/pull/871

I used of fork of the package you indicated because it's more maintained (see https://github.com/sanathkr/go-npm/issues/15).

There's a contribution I just made which is a blocker to make it work on Windows: https://github.com/gzuidhof/go-npm/pull/5.

**Comment by nmnmcc** [comment]
https://www.npmjs.com/package/@nmnmcc/task#provenance

**Comment by pd93** [comment]
Please note we have an official npm package here: https://www.npmjs.com/package/@go-task/cli

**Comment by nmnmcc** [comment]
Thanks for the heads-up, @pd93 — I knew about `@go-task/cli` before publishing mine, but chose to take a different approach. Happy to see there's an official package. 🙏

For context (in case it's useful to anyone landing here), the package I published takes a slightly different distribution approach:

- It ships per-platform binaries as separate sub-packages selected via `optionalDependencies`, so only the binary for the current platform is fetched.
- No `postinstall` script runs at install time, and the binary is served directly from the npm registry (or its mirror) rather than downloaded from a third party.
- Each release is published with [npm provenance](https://docs.npmjs.com/generating-provenance-statements), which lets users verify it was built by this repo's GitHub Actions.

Totally happy to defer to the official package — just sharing the approach in case any of it is interesting to the maintainers or useful for users with stricter install-time constraints.
