### ISSUE TITLE
Parsing errors encountered after upgrade to 3.19.1

### ISSUE THREAD

**Issue by dotnwat** [go-task/task#979]
Hi we at @redpanda-data have been using task now for a couple years and really enjoy it. Part of our CI does automated task installs, and the latest 3.19.1 we are experiencing a parsing error.

```
STEP 7/7: run cd /src/redpanda && task dev:bootstrap                                                                                                                                           
task: Failed to parse vtools/taskfiles/ci.yml:                                                                                                                                                 
yaml: line 485: invalid keys in command                                         
```

I looked at this part of the `ci.yml` file and git blame reports that no changes have been made in months. I'm curious if something in the parsing changed, or perhaps parsing became more strict and we may have a rogue invisible character or something.

I can't share the ci.yml file directly, but I may be able to create a minified reproducer if that is helpful. 

- Task version: 3.19.1
- Operating System: Linux

**Comment by seblw** [comment]
Downgrading to v3.19.0 helps, but yeah, same problem.

**Comment by pd93** [comment]
This is likely related to #959.

> I may be able to create a minified reproducer if that is helpful

This would definitely be useful as I'm not able to reproduce with any of my Taskfiles.

**Comment by andreynering** [comment]
Thanks you two for reporting.

We probably need a reproduce to understand what is happening.

Is it possible that you're additional keys with `cmd:`? Also, are you using YAML anchors on these files?

**Comment by pd93** [comment]
@dotnwat thanks for providing a repro. From what I can tell, the snippet you provided is valid YAML. However, it is interpreting `echo '~~~ Building redpanda :` as the key and the rest of the string as a value. Since this is not a valid command key in Task, you are seeing the error: `invalid keys in command`. I've added a syntax highlighted version of your YAML below so you can see how its being interpreted.

To avoid this, you need to quote the entire value so that the YAML parser correctly interprets it as a string rather than a map. I've added a fixed version of the task below.

```yaml
version: '3'

tasks:
  rp-cov-build:
    cmds:
      - echo '~~~ Building redpanda :cpp: with code coverage enabled :coverage:'

  rp-cov-build-fixed:
    cmds:
      - 'echo "~~~ Building redpanda :cpp: with code coverage enabled :coverage:"'
```

As you correctly stated in your original comment, this was not causing errors previously because we were using an older version of the YAML parser that was much more forgiving. We now require that everything be valid YAML and the correct types.

As there were a few different reports, I'll leave this open for now in case there are other issues. @dotnwat @brokenpip3 @seblw Please feel free to add any other reproduceable samples and I'll take a look.

**Comment by dotnwat** [comment]
Thanks a lot for the analysis @pd93. We'll get our yaml files updated to be compliant. Feel free to close whenever you want.

**Comment by OldTechNeck** [comment]
Just a kudos/thank you for leaving this open so I can find it.  I've been beating my brains out trying to figure out why a simple command of:

cmds:
  - echo "Value is: $VALUE"

is breaking :)
